### ISSUE TITLE
Docs Favicon Logo Update

### ISSUE THREAD

**Issue by ThomasOpenDollar** [open-dollar/od-docs#67]
Update Open Dollar Docs with new Favicon logo.

**Comment by jahabeebs** [comment]
closed in this commit https://github.com/open-dollar/od-docs/commit/05f07b228ac3b7718e9f7b9a9d3b556756a4d525 and fixed the docs in general in this commit https://github.com/open-dollar/od-docs/pull/68.

will create a PR to main
